### ISSUE TITLE
Test suite started to fail (with newest DBD::SQLite?)

### ISSUE THREAD

**Issue by eserte** [GrantStreetGroup/DBIx-OnlineDDL#2]
See subject. A sample fail report: http://www.cpantesters.org/cpan/report/cd567eec-0c1a-11e9-9723-d56d1ac92721

It seems that this failure happens with recent DBD::SQLite (@charsbar FYI).

**Comment by SineSwiper** [comment]
This is most likely related to the [recent SQLite change](https://www.sqlite.org/changes.html) in 3.25.0:

> Fix table rename feature so that it also updates references to the renamed table in triggers and views.

Since SQLite does not yet support DDL against tables for adding/dropping/renaming FKs, we'll have to make use of their `legacy_alter_table` pragma variable.  (Certainly better than running OnlineDDL against every child table just to rename a FK, which then becomes some infinite loop of rename operations...)
